# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "226b7db4be96cc6154d0eeb8aaa17f28"
name = "foxtail-designs dev"
handle = "foxtail-designs-dev"
application_url = "https://star-loose-changing-cap.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e05d69eb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://star-loose-changing-cap.trycloudflare.com/auth/callback",
  "https://star-loose-changing-cap.trycloudflare.com/auth/shopify/callback",
  "https://star-loose-changing-cap.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
