# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04647ec21da57e20574c4c98d2ce4ce5"
name = "foxtail-designs"
handle = "foxtail-designs"
application_url = "https://elliott-legislature-cycles-bracket.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7370ec5b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://elliott-legislature-cycles-bracket.trycloudflare.com/auth/callback",
  "https://elliott-legislature-cycles-bracket.trycloudflare.com/auth/shopify/callback",
  "https://elliott-legislature-cycles-bracket.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
