# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "276741cc496195767e491f77bc719d46"
name = "foxtail-designs"
handle = "foxtail-designs-1"
application_url = "https://tracks-latter-armed-signatures.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e05d69eb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tracks-latter-armed-signatures.trycloudflare.com/auth/callback",
  "https://tracks-latter-armed-signatures.trycloudflare.com/auth/shopify/callback",
  "https://tracks-latter-armed-signatures.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
