# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "276741cc496195767e491f77bc719d46"
name = "foxtail-designs"
handle = "foxtail-designs-1"
application_url = "https://ge-urw-violations-specs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e05d69eb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,write_products"

[auth]
redirect_urls = [
  "https://ge-urw-violations-specs.trycloudflare.com/auth/callback",
  "https://ge-urw-violations-specs.trycloudflare.com/auth/shopify/callback",
  "https://ge-urw-violations-specs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
